In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [2]:
botname = 'ds6600'
version = '0.0'
purpose = 'Class demo'
email = 'jkropko@virginia.edu'
useragent = f'{botname}/{version} ({purpose}; {email}) python-requests/{requests.__version__}'
headers = {'User-Agent': useragent}

In [3]:
house_committees_url = 'https://clerk.house.gov/committees/'

r = requests.get(house_committees_url, headers=headers)
r

In [6]:
mysoup = BeautifulSoup(r.text, 'html.parser')
#mysoup

Anatomy of HTML

```
<tag attribute="value"> navigable string </tag> 

```

In [10]:
mylist = mysoup.find_all('a', attrs = {'class': 'library-committeePanel-subItems'})

In [17]:
{'url': 'https://clerk.house.gov' + mylist[0]['href'],
 'committee_name': mylist[0].text.strip()}

{'url': 'https://clerk.house.gov/committees/AG22',
 'committee_name': 'Commodity Markets, Digital Assets, and Rural Development'}

In [19]:
committee_df = pd.DataFrame([{'url': 'https://clerk.house.gov' + x['href'],
 'committee_name': x.text.strip()} for x in mylist])
committee_df

,url,committee_name
0,https://clerk.house.gov/committees/AG22,"Commodity Markets, Digital Assets, and Rural D..."
1,https://clerk.house.gov/committees/AG14,"Conservation, Research, and Biotechnology"
2,https://clerk.house.gov/committees/AG15,Forestry and Horticulture
3,https://clerk.house.gov/committees/AG16,"General Farm Commodities, Risk Management, and..."
4,https://clerk.house.gov/committees/AG29,"Livestock, Dairy, and Poultry"
...,...,...
105,https://clerk.house.gov/committees/IG04,Defense Intelligence and Overhead Architecture
106,https://clerk.house.gov/committees/IG06,National Intelligence Enterprise
107,https://clerk.house.gov/committees/IG02,National Security Agency and Cyber
108,https://clerk.house.gov/committees/IG11,Open Source Intelligence
109,https://clerk.house.gov/committees/IG09,Oversight and Investigations

In [22]:
url = committee_df['url'][0]

In [23]:
r = requests.get(url, headers=headers)
r

In [25]:
mysoup = BeautifulSoup(r.text, 'html.parser')

In [29]:
mylist = mysoup.find_all('a', attrs = {'title':'View Profile'})

bioguideIds = [x['href'].replace('/Members/', '') for x in mylist]
pd.DataFrame({'committee': committee_df['committee_name'][0],
              'bioguideId': bioguideIds})

                                            committee bioguideId
0   Commodity Markets, Digital Assets, and Rural D...    J000301
1   Commodity Markets, Digital Assets, and Rural D...    R000612
2   Commodity Markets, Digital Assets, and Rural D...    L000491
3   Commodity Markets, Digital Assets, and Rural D...    S001189
4   Commodity Markets, Digital Assets, and Rural D...    R000603
5   Commodity Markets, Digital Assets, and Rural D...    M000871
6   Commodity Markets, Digital Assets, and Rural D...    C001039
7   Commodity Markets, Digital Assets, and Rural D...    F000475
8   Commodity Markets, Digital Assets, and Rural D...    N000193
9   Commodity Markets, Digital Assets, and Rural D...    B001327
10  Commodity Markets, Digital Assets, and Rural D...    M001233
11  Commodity Markets, Digital Assets, and Rural D...    T000490
12  Commodity Markets, Digital Assets, and Rural D...    D000230
13  Commodity Markets, Digital Assets, and Rural D...    B001315
14  Commodity Markets, Digital Assets, and Rural D...    J000309
15  Commodity Markets, Digital Assets, and Rural D...    T000488
16  Commodity Markets, Digital Assets, and Rural D...    G000605
17  Commodity Markets, Digital Assets, and Rural D...    M001237
18  Commodity Markets, Digital Assets, and Rural D...    F000481
19  Commodity Markets, Digital Assets, and Rural D...    V000138
20  Commodity Markets, Digital Assets, and Rural D...    M001231
21  Commodity Markets, Digital Assets, and Rural D...    M001232

In [31]:
def congress_spider(url, committee):
    print(committee)
    r = requests.get(url, headers=headers)
    mysoup = BeautifulSoup(r.text, 'html.parser')
    mylist = mysoup.find_all('a', attrs = {'title':'View Profile'})
    bioguideIds = [x['href'].replace('/Members/', '') for x in mylist]
    return {'committee': committee,
              'bioguideId': bioguideIds}

In [33]:
full_committee_list = [congress_spider(u,c) 
                       for u, c in zip(committee_df['url'], committee_df['committee_name'])]

Commodity Markets, Digital Assets, and Rural Development
Conservation, Research, and Biotechnology
Forestry and Horticulture
General Farm Commodities, Risk Management, and Credit
Livestock, Dairy, and Poultry
Nutrition and Foreign Agriculture
Agriculture, Rural Development, Food and Drug Administration, and Related Agencies
Commerce, Justice, Science, and Related Agencies
Defense
Energy and Water Development and Related Agencies
Financial Services and General Government
Homeland Security
Interior, Environment, and Related Agencies
Labor, Health and Human Services, Education, and Related Agencies
Legislative Branch
Military Construction, Veterans Affairs, and Related Agencies
National Security, Department of State, and Related Programs
Transportation, Housing and Urban Development, and Related Agencies
Cyber, Information Technologies, and  Innovation
Intelligence and Special Operations
Military Personnel
Readiness
Seapower and Projection Forces
Strategic Forces
Tactical Air and Land Forces
Early Childhood, Elementary, and Secondary Education
Health, Employment, Labor, and Pensions
Higher Education and Workforce Development
Workforce Protections
Commerce, Manufacturing, and Trade
Communications and Technology
Energy
Environment
Health
Oversight and Investigations
Capital Markets
Digital Assets, Financial Technology, and Artificial Intelligence
Financial Institutions
Housing and Insurance
National Security, Illicit Finance, and  International Financial Institutions
Oversight and Investigations
Africa
East Asia and Pacific
Europe
Middle East and North Africa
Oversight and Intelligence
South and Central Asia
Western Hemisphere
Border Security and Enforcement
Counterterrorism and Intelligence
Cybersecurity and Infrastructure Protection
Emergency Management and Technology
Oversight, Investigations, and Accountability
Transportation and Maritime Security
Elections
Modernization and Innovation
The Administrative State, Regulatory Reform, and Antitrust
The Constitution and Limited Government
Courts, Intellectual Property, Artificial Intelligence, and the Internet
Crime and Federal Government Surveillance
Immigration Integrity, Security, and Enforcement
Oversight
Select Subcommittee to Investigate the Remaining Questions Surrounding January 6, 2021
Energy and Mineral Resources
Federal Lands
Indian and Insular Affairs
Oversight and Investigations
Water, Wildlife and Fisheries
Cybersecurity, Information Technology, and Government Innovation
Delivering on Government Efficiency
Economic Growth, Energy Policy, and Regulatory Affairs
Federal Law Enforcement
Government Operations
Health Care and Financial Services
Military and Foreign Affairs
Legislative and Budget Process
Rules and Organization of the House
Energy
Environment
Investigations and Oversight
Research and Technology
Space and Aeronautics
Contracting and Infrastructure
Economic Growth, Tax, and Capital Access
Innovation, Entrepreneurship, and Workforce Development
Oversight, Investigations, and Regulations
Rural Development, Energy, and Supply Chains
Aviation
Coast Guard and Maritime Transportation
Economic Development, Public Buildings, and Emergency Management
Highways and Transit
Railroads, Pipelines, and Hazardous Materials
Water Resources and Environment
Disability Assistance and Memorial Affairs
Economic Opportunity
Health
Oversight and Investigations
Technology Modernization
Health
Oversight
Social Security
Tax
Trade
Work and Welfare
Central Intelligence Agency
Defense Intelligence and Overhead Architecture
National Intelligence Enterprise
National Security Agency and Cyber
Open Source Intelligence
Oversight and Investigations

In [ ]:
list_of_dfs = [pd.DataFrame(x) for x in full_committee_list]
#list_of_dfs[1]
full_df = pd.concat(list_of_dfs)
full_df

                                    committee bioguideId
0   Conservation, Research, and Biotechnology    L000491
1   Conservation, Research, and Biotechnology    B001307
2   Conservation, Research, and Biotechnology    B001298
3   Conservation, Research, and Biotechnology    F000446
4   Conservation, Research, and Biotechnology    M001211
5   Conservation, Research, and Biotechnology    R000612
6   Conservation, Research, and Biotechnology    J000304
7   Conservation, Research, and Biotechnology    N000189
8   Conservation, Research, and Biotechnology    B001327
9   Conservation, Research, and Biotechnology    M001233
10  Conservation, Research, and Biotechnology    T000487
11  Conservation, Research, and Biotechnology    A000370
12  Conservation, Research, and Biotechnology    D000629
13  Conservation, Research, and Biotechnology    B001315
14  Conservation, Research, and Biotechnology    S001225
15  Conservation, Research, and Biotechnology    V000136
16  Conservation, Research, and Biotechnology    V000138
17  Conservation, Research, and Biotechnology    M001231
18  Conservation, Research, and Biotechnology    M001232