In [1]:
import numpy as np
import pandas as pd
import os
import requests
import json
import dotenv

In [2]:
dotenv.load_dotenv()

True

In [3]:
congresskey = os.getenv('congresskey')

There are five pieces of information you need to navigate any API and its poor documentation:

1. How you get an API key (or another credential) to get access to the data (check)

2. Root: the beginning of the URL for any endpoint contained within the API

A URL: `root / endpoint ? parameters`

3. Endpoint: the middle of the URL, specifies which data store on the API to access

4. Parameters: ways to control what exactly is returned when you access an endpoint. Two kinds of parameter:

* Query parameters (appear after the ?, but requests formats this for you using the `params` argument)
* Path parameters -- supposed to be entered as part of the endpoint itself

5. How to supply your API key back to the API to prove that you are you

In [4]:
# style: I don't like putting a slash at the end of the root, because the slash is usually part of the endpoint
root = 'https://api.congress.gov/v3' 

endpoint = '/member'

params = {'format': 'json',
          'currentMember': 'true',
          'api_key': congresskey}

In [5]:
r = requests.get(root + endpoint, params=params)
r

In [6]:
r.text

'{\n    "members": [\n        {\n            "bioguideId": "W000832",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg"\n            },\n            "district": 14,\n            "name": "Wahab, Aisha",\n            "partyName": "Democratic",\n            "state": "California",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/W000832?format=json"\n        },\n        {\n            "bioguideId": "B001328",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg"\n            },\n            "district": 13,\n            "name": "Blair, Everton",\n            "partyName": "Democratic",\n            "state": "Georgia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/B001328?format=json"\n        },\n        {\n            "bioguideId": "G000607",\n            "depiction": {\n                "imageUrl": "https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg"\n            },\n            "district": 1,\n            "name": "Gallagher, James",\n            "partyName": "Republican",\n            "state": "California",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/G000607?format=json"\n        },\n        {\n            "bioguideId": "M001246",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg"\n            },\n            "district": 11,\n            "name": "Mejia, Analilia",\n            "partyName": "Democratic",\n            "state": "New Jersey",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/M001246?format=json"\n        },\n        {\n            "bioguideId": "F000485",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg"\n            },\n            "district": 14,\n            "name": "Fuller, Clay",\n            "partyName": "Republican",\n            "state": "Georgia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/F000485?format=json"\n        },\n        {\n            "bioguideId": "M001245",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg"\n            },\n            "district": 18,\n            "name": "Menefee, Christian D.",\n            "partyName": "Democratic",\n            "state": "Texas",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2026\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/M001245?format=json"\n        },\n        {\n            "bioguideId": "V000139",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg"\n            },\n            "district": 7,\n            "name": "Van Epps, Matt",\n            "partyName": "Republican",\n            "state": "Tennessee",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/V000139?format=json"\n        },\n        {\n            "bioguideId": "G000606",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6915fa2585b49de40f52cacb_200.jpg"\n            },\n            "district": 7,\n            "name": "Grijalva, Adelita S.",\n            "partyName": "Democratic",\n            "state": "Arizona",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/G000606?format=json"\n        },\n        {\n            "bioguideId": "P000622",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg"\n            },\n            "district": 1,\n            "name": "Patronis, Jimmy",\n            "partyName": "Republican",\n            "state": "Florida",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/P000622?format=json"\n        },\n        {\n            "bioguideId": "F000484",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg"\n            },\n            "district": 6,\n            "name": "Fine, Randy",\n            "partyName": "Republican",\n            "state": "Florida",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/F000484?format=json"\n        },\n        {\n            "bioguideId": "V000138",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg"\n            },\n            "district": 7,\n            "name": "Vindman, Eugene Simon",\n            "partyName": "Democratic",\n            "state": "Virginia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/V000138?format=json"\n        },\n        {\n            "bioguideId": "T000490",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg"\n            },\n            "district": 2,\n            "name": "Taylor, David J.",\n            "partyName": "Republican",\n            "state": "Ohio",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/T000490?format=json"\n        },\n        {\n            "bioguideId": "S001230",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg"\n            },\n            "district": 10,\n            "name": "Subramanyam, Suhas",\n            "partyName": "Democratic",\n            "state": "Virginia",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/S001230?format=json"\n        },\n        {\n            "bioguideId": "S001229",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg"\n            },\n            "district": 6,\n            "name": "Shreve, Jefferson",\n            "partyName": "Republican",\n            "state": "Indiana",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/S001229?format=json"\n        },\n        {\n            "bioguideId": "S001228",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg"\n            },\n            "district": 2,\n            "name": "Schmidt, Derek",\n            "partyName": "Republican",\n            "state": "Kansas",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/S001228?format=json"\n        },\n        {\n            "bioguideId": "R000622",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg"\n            },\n            "district": 19,\n            "name": "Riley, Josh",\n            "partyName": "Democratic",\n            "state": "New York",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/R000622?format=json"\n        },\n        {\n            "bioguideId": "P000621",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg"\n            },\n            "district": 9,\n            "name": "Pou, Nellie",\n            "partyName": "Democratic",\n            "state": "New Jersey",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/P000621?format=json"\n        },\n        {\n            "bioguideId": "O000177",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67744f970b34857ecc909161_200.jpg"\n            },\n            "district": 3,\n            "name": "Onder, Robert F.",\n            "partyName": "Republican",\n            "state": "Missouri",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/O000177?format=json"\n        },\n        {\n            "bioguideId": "O000176",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg"\n            },\n            "district": 2,\n            "name": "Olszewski, Johnny",\n            "partyName": "Democratic",\n            "state": "Maryland",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/O000176?format=json"\n        },\n        {\n            "bioguideId": "M001240",\n            "depiction": {\n                "attribution": "Image courtesy of the Member",\n                "imageUrl": "https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg"\n            },\n            "district": 6,\n            "name": "McDowell, Addison P.",\n            "partyName": "Republican",\n            "state": "North Carolina",\n            "terms": {\n                "item": [\n                    {\n                        "chamber": "House of Representatives",\n                        "startYear": 2025\n                    }\n                ]\n            },\n            "updateDate": "2026-09-22T07:40:25Z",\n            "url": "https://api.congress.gov/v3/member/M001240?format=json"\n        }\n    ],\n    "pagination": {\n        "count": 539,\n        "next": "https://api.congress.gov/v3/member?currentMember=true&offset=20&limit=20&format=json"\n    },\n    "request": {\n        "contentType": "application/json",\n        "format": "json"\n    }\n}'

In [7]:
r.json()

{'members': [{'bioguideId': 'W000832',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
   'district': 14,
   'name': 'Wahab, Aisha',
   'partyName': 'Democratic',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/W000832?format=json'},
  {'bioguideId': 'B001328',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg'},
   'district': 13,
   'name': 'Blair, Everton',
   'partyName': 'Democratic',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/B001328?format=json'},
  {'bioguideId': 'G000607',
   'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
   'district': 1,
   'name': 'Gallagher, James',
   'partyName': 'Republican',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
  {'bioguideId': 'M001246',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
   'district': 11,
   'name': 'Mejia, Analilia',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
  {'bioguideId': 'F000485',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
   'district': 14,
   'name': 'Fuller, Clay',
   'partyName': 'Republican',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
  {'bioguideId': 'M001245',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
   'district': 18,
   'name': 'Menefee, Christian D.',
   'partyName': 'Democratic',
   'state': 'Texas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
  {'bioguideId': 'V000139',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
   'district': 7,
   'name': 'Van Epps, Matt',
   'partyName': 'Republican',
   'state': 'Tennessee',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
  {'bioguideId': 'G000606',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6915fa2585b49de40f52cacb_200.jpg'},
   'district': 7,
   'name': 'Grijalva, Adelita S.',
   'partyName': 'Democratic',
   'state': 'Arizona',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/G000606?format=json'},
  {'bioguideId': 'P000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
   'district': 1,
   'name': 'Patronis, Jimmy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
  {'bioguideId': 'F000484',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
   'district': 6,
   'name': 'Fine, Randy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
  {'bioguideId': 'V000138',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
   'district': 7,
   'name': 'Vindman, Eugene Simon',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
  {'bioguideId': 'T000490',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
   'district': 2,
   'name': 'Taylor, David J.',
   'partyName': 'Republican',
   'state': 'Ohio',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
  {'bioguideId': 'S001230',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
   'district': 10,
   'name': 'Subramanyam, Suhas',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
  {'bioguideId': 'S001229',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
   'district': 6,
   'name': 'Shreve, Jefferson',
   'partyName': 'Republican',
   'state': 'Indiana',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
  {'bioguideId': 'S001228',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
   'district': 2,
   'name': 'Schmidt, Derek',
   'partyName': 'Republican',
   'state': 'Kansas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
  {'bioguideId': 'R000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
   'district': 19,
   'name': 'Riley, Josh',
   'partyName': 'Democratic',
   'state': 'New York',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
  {'bioguideId': 'P000621',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
   'district': 9,
   'name': 'Pou, Nellie',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
  {'bioguideId': 'O000177',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744f970b34857ecc909161_200.jpg'},
   'district': 3,
   'name': 'Onder, Robert F.',
   'partyName': 'Republican',
   'state': 'Missouri',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/O000177?format=json'},
  {'bioguideId': 'O000176',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
   'district': 2,
   'name': 'Olszewski, Johnny',
   'partyName': 'Democratic',
   'state': 'Maryland',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
  {'bioguideId': 'M001240',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
   'district': 6,
   'name': 'McDowell, Addison P.',
   'partyName': 'Republican',
   'state': 'North Carolina',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/M001240?format=json'}],
 'pagination': {'count': 539,
  'next': 'https://api.congress.gov/v3/member?currentMember=true&offset=20&limit=20&format=json'},
 'request': {'contentType': 'application/json', 'format': 'json'}}

1. User-Agent strings/headers

A piece of text you give to the data server to tell them a bit about who you are and what your system is

2. Navigate a JSON

3. Pagination and rate limits

In [9]:
botname = 'ds6600'
version = '0.0'
purpose = 'Class demonstration'
email = 'jkropko@virginia.edu'
useragent = f'{botname}/{version} ({purpose}; {email}) python-requests/{requests.__version__}'
headers = {'User-Agent': useragent}
headers

{'User-Agent': 'ds6600/0.0 (Class demonstration; jkropko@virginia.edu) python-requests/2.34.2'}

In [10]:
root = 'https://api.congress.gov/v3'
endpoint = '/member'
params = {'format': 'json',
          'currentMember': True,
          'api_key': congresskey}

r = requests.get(root + endpoint, params=params, headers=headers)
r

In [12]:
myjson = r.json()
myjson

{'members': [{'bioguideId': 'W000832',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a986b632a68122e10181e6b_200.jpg'},
   'district': 14,
   'name': 'Wahab, Aisha',
   'partyName': 'Democratic',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/W000832?format=json'},
  {'bioguideId': 'B001328',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a9869d92a68122e10181e62_200.jpg'},
   'district': 13,
   'name': 'Blair, Everton',
   'partyName': 'Democratic',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/B001328?format=json'},
  {'bioguideId': 'G000607',
   'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
   'district': 1,
   'name': 'Gallagher, James',
   'partyName': 'Republican',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
  {'bioguideId': 'M001246',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
   'district': 11,
   'name': 'Mejia, Analilia',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
  {'bioguideId': 'F000485',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
   'district': 14,
   'name': 'Fuller, Clay',
   'partyName': 'Republican',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
  {'bioguideId': 'M001245',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
   'district': 18,
   'name': 'Menefee, Christian D.',
   'partyName': 'Democratic',
   'state': 'Texas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
  {'bioguideId': 'V000139',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
   'district': 7,
   'name': 'Van Epps, Matt',
   'partyName': 'Republican',
   'state': 'Tennessee',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
  {'bioguideId': 'G000606',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6915fa2585b49de40f52cacb_200.jpg'},
   'district': 7,
   'name': 'Grijalva, Adelita S.',
   'partyName': 'Democratic',
   'state': 'Arizona',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/G000606?format=json'},
  {'bioguideId': 'P000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
   'district': 1,
   'name': 'Patronis, Jimmy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
  {'bioguideId': 'F000484',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
   'district': 6,
   'name': 'Fine, Randy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
  {'bioguideId': 'V000138',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
   'district': 7,
   'name': 'Vindman, Eugene Simon',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
  {'bioguideId': 'T000490',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
   'district': 2,
   'name': 'Taylor, David J.',
   'partyName': 'Republican',
   'state': 'Ohio',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
  {'bioguideId': 'S001230',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
   'district': 10,
   'name': 'Subramanyam, Suhas',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
  {'bioguideId': 'S001229',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
   'district': 6,
   'name': 'Shreve, Jefferson',
   'partyName': 'Republican',
   'state': 'Indiana',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
  {'bioguideId': 'S001228',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
   'district': 2,
   'name': 'Schmidt, Derek',
   'partyName': 'Republican',
   'state': 'Kansas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
  {'bioguideId': 'R000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
   'district': 19,
   'name': 'Riley, Josh',
   'partyName': 'Democratic',
   'state': 'New York',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
  {'bioguideId': 'P000621',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
   'district': 9,
   'name': 'Pou, Nellie',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
  {'bioguideId': 'O000177',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744f970b34857ecc909161_200.jpg'},
   'district': 3,
   'name': 'Onder, Robert F.',
   'partyName': 'Republican',
   'state': 'Missouri',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/O000177?format=json'},
  {'bioguideId': 'O000176',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
   'district': 2,
   'name': 'Olszewski, Johnny',
   'partyName': 'Democratic',
   'state': 'Maryland',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
  {'bioguideId': 'M001240',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
   'district': 6,
   'name': 'McDowell, Addison P.',
   'partyName': 'Republican',
   'state': 'North Carolina',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-09-22T07:40:25Z',
   'url': 'https://api.congress.gov/v3/member/M001240?format=json'}],
 'pagination': {'count': 539,
  'next': 'https://api.congress.gov/v3/member?currentMember=True&offset=20&limit=20&format=json'},
 'request': {'contentType': 'application/json', 'format': 'json'}}

In [20]:
myjson['members'][0]['terms']['item'][0]['chamber']

'House of Representatives'

Record path -- somewhere in the JSON is a list where each item is one row of the dataframe youn want to build. The record path is the sequence of keys to call to arrive at this list.

In this case the record path is: just members

In [21]:
congress_df = pd.json_normalize(myjson, record_path=['members'])
congress_df

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,W000832,14,"Wahab, Aisha",Democratic,California,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/W000832?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a986b632a...,"[{'chamber': 'House of Representatives', 'star..."
1,B001328,13,"Blair, Everton",Democratic,Georgia,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/B001328?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a9869d92a...,"[{'chamber': 'House of Representatives', 'star..."
2,G000607,1,"Gallagher, James",Republican,California,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/G000607?for...,NaN,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star..."
3,M001246,11,"Mejia, Analilia",Democratic,New Jersey,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/M001246?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star..."
4,F000485,14,"Fuller, Clay",Republican,Georgia,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/F000485?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star..."
5,M001245,18,"Menefee, Christian D.",Democratic,Texas,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/M001245?for...,Image courtesy of the Member,https://www.congress.gov/img/member/698206b2eb...,"[{'chamber': 'House of Representatives', 'star..."
6,V000139,7,"Van Epps, Matt",Republican,Tennessee,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/V000139?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6931b7d5f4...,"[{'chamber': 'House of Representatives', 'star..."
7,G000606,7,"Grijalva, Adelita S.",Democratic,Arizona,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/G000606?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6915fa2585...,"[{'chamber': 'House of Representatives', 'star..."
8,P000622,1,"Patronis, Jimmy",Republican,Florida,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/P000622?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67efdb991b...,"[{'chamber': 'House of Representatives', 'star..."
9,F000484,6,"Fine, Randy",Republican,Florida,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/F000484?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67efda8c1b...,"[{'chamber': 'House of Representatives', 'star..."
10,V000138,7,"Vindman, Eugene Simon",Democratic,Virginia,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/V000138?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6774617a0b...,"[{'chamber': 'House of Representatives', 'star..."
11,T000490,2,"Taylor, David J.",Republican,Ohio,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/T000490?for...,Image courtesy of the Member,https://www.congress.gov/img/member/677460190b...,"[{'chamber': 'House of Representatives', 'star..."
12,S001230,10,"Subramanyam, Suhas",Democratic,Virginia,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/S001230?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6797be8bc7...,"[{'chamber': 'House of Representatives', 'star..."
13,S001229,6,"Shreve, Jefferson",Republican,Indiana,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/S001229?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745f0e0b...,"[{'chamber': 'House of Representatives', 'star..."
14,S001228,2,"Schmidt, Derek",Republican,Kansas,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/S001228?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745ec50b...,"[{'chamber': 'House of Representatives', 'star..."
15,R000622,19,"Riley, Josh",Democratic,New York,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/R000622?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745e360b...,"[{'chamber': 'House of Representatives', 'star..."
16,P000621,9,"Pou, Nellie",Democratic,New Jersey,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/P000621?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67745d3b0b...,"[{'chamber': 'House of Representatives', 'star..."
17,O000177,3,"Onder, Robert F.",Republican,Missouri,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/O000177?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67744f970b...,"[{'chamber': 'House of Representatives', 'star..."
18,O000176,2,"Olszewski, Johnny",Democratic,Maryland,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/O000176?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a3974507d...,"[{'chamber': 'House of Representatives', 'star..."
19,M001240,6,"McDowell, Addison P.",Republican,North Carolina,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/M001240?for...,Image courtesy of the Member,https://www.congress.gov/img/member/67744e930b...,"[{'chamber': 'House of Representatives', 'star..."

In [23]:
params['limit'] = '250'
#params

In [26]:
r = requests.get(root + endpoint, params=params, headers=headers)
myjson = r.json()
congress_df = pd.json_normalize(myjson, record_path=['members'])

pd.set_option('display.max_rows', 10)
congress_df

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,W000832,14.0,"Wahab, Aisha",Democratic,California,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/W000832?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a986b632a...,"[{'chamber': 'House of Representatives', 'star..."
1,B001328,13.0,"Blair, Everton",Democratic,Georgia,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/B001328?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a9869d92a...,"[{'chamber': 'House of Representatives', 'star..."
2,G000607,1.0,"Gallagher, James",Republican,California,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/G000607?for...,NaN,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star..."
3,M001246,11.0,"Mejia, Analilia",Democratic,New Jersey,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/M001246?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star..."
4,F000485,14.0,"Fuller, Clay",Republican,Georgia,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/F000485?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star..."
...,...,...,...,...,...,...,...,...,...,...
245,T000480,4.0,"Timmons, William R.",Republican,South Carolina,2026-09-22T07:40:22Z,https://api.congress.gov/v3/member/T000480?for...,Image courtesy of the Member,https://www.congress.gov/img/member/t000480_20...,"[{'chamber': 'House of Representatives', 'star..."
246,R000610,14.0,"Reschenthaler, Guy",Republican,Pennsylvania,2026-09-22T07:40:22Z,https://api.congress.gov/v3/member/R000610?for...,Image courtesy of the Member,https://www.congress.gov/img/member/r000610_20...,"[{'chamber': 'House of Representatives', 'star..."
247,J000302,13.0,"Joyce, John",Republican,Pennsylvania,2026-09-22T07:40:22Z,https://api.congress.gov/v3/member/J000302?for...,Image courtesy of the Member,https://www.congress.gov/img/member/j000302_20...,"[{'chamber': 'House of Representatives', 'star..."
248,M001204,9.0,"Meuser, Daniel",Republican,Pennsylvania,2026-09-22T07:40:22Z,https://api.congress.gov/v3/member/M001204?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6776ebbf4f...,"[{'chamber': 'House of Representatives', 'star..."
249,H001085,6.0,"Houlahan, Chrissy",Democratic,Pennsylvania,2026-09-22T07:40:22Z,https://api.congress.gov/v3/member/H001085?for...,Image courtesy of the Member,https://www.congress.gov/img/member/681bc0e6b7...,"[{'chamber': 'House of Representatives', 'star..."

In [31]:
params['offset'] = '600'
r = requests.get(root + endpoint, params=params, headers=headers)
myjson = r.json()
myjson
#congress_df = pd.json_normalize(myjson, record_path=['members'])
#congress_df

{'members': [],
 'pagination': {'count': 539,
  'prev': 'https://api.congress.gov/v3/member?currentMember=True&offset=350&limit=250&format=json'},
 'request': {'contentType': 'application/json', 'format': 'json'}}

In [34]:
i = 0
still_members = True
congress_json = []
while still_members:
    print(i)
    params['offset'] = i
    r = requests.get(root + endpoint, params=params, headers=headers)
    myjson = r.json()
    still_members = len(myjson['members']) > 0
    congress_json.extend(myjson['members'])
    i = i + 250

0
250
500
750

In [36]:
len(congress_json)

539

In [37]:
congress_df = pd.json_normalize(congress_json)

In [38]:
congress_df

,bioguideId,district,name,partyName,state,updateDate,url,depiction.attribution,depiction.imageUrl,terms.item
0,W000832,14.0,"Wahab, Aisha",Democratic,California,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/W000832?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a986b632a...,"[{'chamber': 'House of Representatives', 'star..."
1,B001328,13.0,"Blair, Everton",Democratic,Georgia,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/B001328?for...,Image courtesy of the Member,https://www.congress.gov/img/member/6a9869d92a...,"[{'chamber': 'House of Representatives', 'star..."
2,G000607,1.0,"Gallagher, James",Republican,California,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/G000607?for...,NaN,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star..."
3,M001246,11.0,"Mejia, Analilia",Democratic,New Jersey,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/M001246?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star..."
4,F000485,14.0,"Fuller, Clay",Republican,Georgia,2026-09-22T07:40:25Z,https://api.congress.gov/v3/member/F000485?for...,Image courtesy of the Member,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star..."
...,...,...,...,...,...,...,...,...,...,...
534,B001267,NaN,"Bennet, Michael F.",Democratic,Colorado,2026-03-08T10:30:30Z,https://api.congress.gov/v3/member/B001267?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001267_20...,"[{'chamber': 'Senate', 'startYear': 2009}]"
535,B001261,NaN,"Barrasso, John",Republican,Wyoming,2026-03-08T10:30:29Z,https://api.congress.gov/v3/member/B001261?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001261_20...,"[{'chamber': 'Senate', 'startYear': 2007}]"
536,B001299,NaN,"Banks, Jim",Republican,Indiana,2026-03-08T10:30:27Z,https://api.congress.gov/v3/member/B001299?for...,Official U.S. Senate Photo,https://www.congress.gov/img/member/677d83cbfd...,"[{'chamber': 'House of Representatives', 'endY..."
537,B001230,NaN,"Baldwin, Tammy",Democratic,Wisconsin,2026-03-08T10:30:26Z,https://api.congress.gov/v3/member/B001230?for...,"<a href=""http://www.senate.gov/artandhistory/h...",https://www.congress.gov/img/member/b001230_20...,"[{'chamber': 'House of Representatives', 'endY..."
538,A000382,NaN,"Alsobrooks, Angela D.",Democratic,Maryland,2026-03-08T10:30:24Z,https://api.congress.gov/v3/member/A000382?for...,NaN,https://www.congress.gov/img/member/67acdbbf04...,"[{'chamber': 'Senate', 'startYear': 2025}]"